version: '3.10'

services:
    web:
      build: .
      command: python /code/manage.py runserver 0.0.0.0:8001
      environment:
      - SECRET_KEY=django-insecure-j0-_%$^xm&$8=z)v*rfj+9*hg&ifa&e#*gip=yn=kaba%m4_9e
      - DEBUG=1
      ports:
        - "8001:8001"
      volumes:
        - .:/code
      depends_on:
        - db

    db:
      image: postgres:12.2
      restart: always
      environment:
        - POSTGRES_DB=postgres
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres

volumes:
    db_data: