# Generated by Django 4.0.6 on 2022-08-10 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='category',
            field=models.CharField(choices=[('Arts', 'Arts'), ('African Fashion & Fabric', 'African Fashion & Fabric'), ('Bars/Lounges', 'Bars/Lounges'), ('Coffee', 'Coffee'), ('Grocery', 'Grocery'), ('Information Technology', 'Information Technology'), ('Restaurants', 'Restaurants'), ('Others', 'Others')], default='Restaurants', max_length=100),
        ),
    ]
